### ISSUE TITLE
Create a CSV file with title and text in plaintext for Amazon Mechnical Turk with 2000 unique support questions

### ISSUE THREAD

**Issue by rtanglao** [mlopatka/CANOSP2020#92] opened 2020-03-03 20:58 UTC
Requirements:
1. The CSV file should have the following headers ([sample file with 9 questions](https://docs.google.com/spreadsheets/d/1hFXPPq2k6Tl8rAlwpUy7MqhGNe8YV8Tyfxp6bJrBlDI/edit#gid=541869271)):
sumo-ticket-title,sumo-ticket-text
2. The ticket text should have the HTML parsed out to plain text.
3. The file should have the the 200 tickets we have already tagged. 
4. And then a further 1800 selected randomly from our giant file of support tickets
5. There may be some overlap in 3. Please make sure the file has exactly 2000 unique tickets.

**Comment by Ana16boo** [comment] 2020-03-03 22:10
Do you think we need to include non-English tickets for this case?

**Comment by willfenton** [comment] 2020-03-04 16:01
The CSV should probably include ticket ID as well, and if we need a version without we can easily remove that column.

**Comment by willfenton** [comment] 2020-03-04 16:03
I can do this at some point today or tomorrow, gonna assign it to myself. If someone wants to take it and get it done earlier, message me on slack.

**Comment by willfenton** [comment] 2020-03-04 16:21
@rtanglao Just to clarify the HTML bit, would this

```
Ticket text bla bla <p>asdfasdf</p> ticket text
```

turn into this?

```
Ticket text bla bla asdfasdf ticket text
```

**Comment by willfenton** [comment] 2020-03-04 17:13
This is how many tickets we have with X annotations, not including SUMO. We'll definitely include the 100 tickets with 7-9 annotations, and then should we include all of the tickets with 2 or 3 annotations, for a total of 300 human-tagged tickets? Or add 100 tickets with 3 annotations to round out the 200?


| # of annotations | # of tickets |
|------------------|--------------|
| 9                | 99           |
| 8                | 0            |
| 7                | 1            |
| 6                | 0            |
| 5                | 0            |
| 4                | 0            |
| 3                | 109          |
| 2                | 191          |
| 1                | 38           |
| Total            | 438          |

@rtanglao @mlopatka

**Comment by mlopatka** [comment] 2020-03-04 18:18
@willfenton Let's include **all** tickets with **any** number (greater than 1) of non-Sumo annotations.
So from the table in the comment above that looks like 400 rather than 300.
Let's get all of those into the Mtruk pipeline and then select an additional 1600 randomly from the most recent 12-18 months.

**Comment by mlopatka** [comment] 2020-03-04 18:19
Keeping in mind these 2000 tickets will be tagged in triplicate by 3 different workers each.

**Comment by willfenton** [comment] 2020-03-04 18:55
Ok, sounds good. Just need some clarification on the HTML preprocessing now

**Comment by mlopatka** [comment] 2020-03-04 19:02
> Ticket text bla bla <p>asdfasdf</p> ticket text
> turn into this?
> Ticket text bla bla asdfasdf ticket text

Yes, you can work under that assumption. 
We **do** need to drop the <ticket ID> column since this is feeding into an automated processing pipeline that expects exactly 2 columns: 
<sumo-ticket-title> and <sumo-ticket-text>

I have confirmed that the annotations output includes the original raw texts for both fields, so we will be able to rejoin the annotations against our own data and re-associate with a ticket-id after tagging is complete.

**Comment by willfenton** [comment] 2020-03-04 22:10
[Sample output from my script, imported into Google Sheets](https://docs.google.com/spreadsheets/d/16D5uzMstZoNX3QJeMKCYMDRjiAc92lX8TrAJTfNV3gA/edit#gid=746933667)

My preprocessing is removing newlines and carriage returns (`\r, \n`) and running it through textpipe's `CleanText` operation

**Closed** 2020-03-05 04:48 UTC
